// Generates src/tokens/tokens.css (CSS variables) and src/tokens/index.ts
// (typed values and var() references) from src/tokens/tokens.json.
import { readFileSync, writeFileSync } from "node:fs";

const tokens = JSON.parse(readFileSync(new URL("../src/tokens/tokens.json", import.meta.url), "utf8"));
const palette = tokens.color.palette;

// "{indigo.600}" → palette value
const resolve = (v) =>
  typeof v === "string" && v.startsWith("{")
    ? v.slice(1, -1).split(".").reduce((o, k) => o?.[k], palette) ?? (() => { throw new Error(`Unknown token ${v}`); })()
    : v;

const kebab = (s) => String(s).replace(/\./g, "_");
const vars = {};
const flat = (prefix, obj) => {
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    if (v && typeof v === "object") flat(`${prefix}-${kebab(k)}`, v);
    else vars[`${prefix}-${kebab(k)}`] = String(v);
  }
};

// Theme-independent tokens.
for (const [name, shades] of Object.entries(palette)) flat(`--lm-${name}`, shades);
flat("--lm-font", tokens.font);
flat("--lm-space", tokens.space);
flat("--lm-radius", tokens.radius);
flat("--lm-motion", tokens.motion);
flat("--lm-z", tokens.z);
flat("--lm-size", tokens.size);

const themed = (theme) => {
  const out = {};
  for (const [k, v] of Object.entries(tokens.color.semantic[theme])) out[`--lm-color-${k}`] = resolve(v);
  for (const [k, v] of Object.entries(tokens.shadow[theme])) out[`--lm-shadow-${k}`] = v;
  tokens.color.chart[theme].forEach((v, i) => (out[`--lm-color-chart-${i + 1}`] = resolve(v)));
  return out;
};
const light = themed("light");
const dark = themed("dark");

const block = (sel, obj, extra = "") => `${sel} {\n${extra}${Object.entries(obj).map(([k, v]) => `  ${k}: ${v};`).join("\n")}\n}\n`;
const css = [
  "/* Generated by scripts/build-tokens.mjs from tokens.json. Do not edit. */",
  block(":root", { ...vars, ...light }, "  color-scheme: light;\n"),
  "/* Dark theme: follows the OS unless data-theme=\"light\" is set, or forced with data-theme=\"dark\". */",
  `@media (prefers-color-scheme: dark) {\n${block(':root:not([data-theme="light"])', dark, "  color-scheme: dark;\n").replace(/^/gm, "  ")}}\n`,
  block('[data-theme="dark"]', dark, "  color-scheme: dark;\n"),
  block('[data-theme="light"]', light, "  color-scheme: light;\n"),
].join("\n");
writeFileSync(new URL("../src/tokens/tokens.css", import.meta.url), css);

// TS: raw values plus var() references for inline styles.
const refs = {};
for (const name of [...Object.keys(vars), ...Object.keys(light)]) refs[name.slice(5)] = `var(${name})`;
const ts = `// Generated by scripts/build-tokens.mjs from tokens.json. Do not edit.
export const tokens = ${JSON.stringify({ ...tokens, $description: undefined }, null, 2)} as const;

/** CSS variable references, e.g. vars["color-accent"] → "var(--lm-color-accent)". */
export const vars = ${JSON.stringify(refs, null, 2)} as const;

export type TokenVar = keyof typeof vars;
`;
writeFileSync(new URL("../src/tokens/index.ts", import.meta.url), ts);
console.log(`tokens: ${Object.keys(vars).length + Object.keys(light).length} variables`);
